version: '3'
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
#      - JACKETT_WEBUI_BASEURL=http://l-j-01.duckdns.org/
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 9117:9117
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: "host"
    environment:
#      - ADVERTISE_IP=http://l-p-01.duckdns.org/
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./downloads/complete:/downloads/complete
      - ./downloads:/downloads
      - ./config:/config
      - ./tv:/tv
      - ./movies:/movies
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
#      - URL_BASE=http://l-r-01.duckdns.org/
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 7878:7878
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ./movies:/movies
      - ./downloads/complete:/downloads/complete
      - ./downloads:/downloads
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
#     - TRANSMISSION_WEB_UI=l-t-01.duckdns.org
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./config:/config
      - ./downloads/complete:/downloads/complete
      - ./downloads:/downloads
      - ./watch:/watch
    restart: unless-stopped
#  duckdns:
#    image: linuxserver/duckdns
#    container_name: duckdns
#    environment:
#      - PUID=1000
#      - PGID=1000
#     - SUBDOMAINS=l-j-01,l-p-01,l-r-01,l-t-01
#      - TOKEN=f52db598-228a-4509-8563-3b2de65d8162
#      - TZ=America/Argentina/Buenos_Aires
#    restart: unless-stopped
